# DataHandler

Illustrates how DataHandler works .

In [ ]:
import sys
sys.path.append('..')


In [1]:
from pathlib import Path
from sklearn import datasets
from pandas import DataFrame
from numpy import c_
import numpy as np


In [2]:
from model_compracomigo.data_handler import DataHandler


2023-06-22 01:11:43.379227: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-06-22 01:11:43.402789: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-06-22 01:11:43.403222: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-06-22 01:11:43.927383: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


## DataHandler read with Pandas

### Behaviour that we would like to replicate w/ Pandas
The pandas results should match. When dealing with cloud, we use s3fs to abstract the same pattern (you can check the tests folder for more indepth garantees that DataHandler works similarly with AWS cloud resources, such as buckets).

In [3]:
iris = datasets.load_iris()
dataset = DataFrame(
    data=c_[iris["data"], iris["target"]],
    columns=iris["feature_names"] + ["target"],
)
dataset.head()


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0     0.0  
1     0.0  
2     0.0  
3     0.0  
4     0.0

### DataHandler w/ Pandas and csv format

#### Writes data to temporary (tmp) folder with csv

In [4]:
dataset_path_csv = str("./tmp/dataset.csv")
with open(dataset_path_csv, "w") as fh:
    iris = datasets.load_iris()
    dataset = DataFrame(
        data=c_[iris["data"], iris["target"]],
        columns=iris["feature_names"] + ["target"],
    )
    dataset.to_csv(path_or_buf=fh)


#### Read csv with DataHandler

In [5]:
data_csv = DataHandler.read_dataset(path=dataset_path_csv)
data_csv.head()


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0     0.0  
1     0.0  
2     0.0  
3     0.0  
4     0.0

### DataHandler w/ Pandas and parquet format

#### Writes data to temporary (tmp) folder with parquet

In [6]:
dataset_path_parquet = str("./tmp/dataset.parquet")
dataset.to_parquet(dataset_path_parquet)


#### Read parquet with DataHandler

In [7]:
data_parquet = DataHandler.read_dataset(path=dataset_path_parquet)
data_parquet.head()


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0     0.0  
1     0.0  
2     0.0  
3     0.0  
4     0.0

## DataHandler read with Numpy Array

### Behaviour that we would like to replicate w/ Numpy Arrays
The results should match. When dealing with cloud, we use s3fs to abstract the same pattern (you can check the tests folder for more indepth garantees that DataHandler works similarly with AWS cloud resources, such as buckets).

In [8]:
iris = datasets.load_iris()
dataset = DataFrame(
    data=c_[iris["data"], iris["target"]],
    columns=iris["feature_names"] + ["target"],
)
dataset.head()


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0     0.0  
1     0.0  
2     0.0  
3     0.0  
4     0.0

### DataHandler w/ Numpy Array and csv format

#### Writes data to temporary (tmp) folder with csv

In [9]:
dataset_path_csv = str("./tmp/dataset.csv")
with open(dataset_path_csv, "w") as fh:
    iris = datasets.load_iris()
    dataset = DataFrame(
        data=c_[iris["data"], iris["target"]],
        columns=iris["feature_names"] + ["target"],
    )
    dataset.to_csv(path_or_buf=fh)
dataset.head()


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0     0.0  
1     0.0  
2     0.0  
3     0.0  
4     0.0

In [10]:
dataset.loc[:, dataset.columns != "target"].to_numpy()[:5], \
dataset["target"].to_numpy()[:5]


(array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2]]),
 array([0., 0., 0., 0., 0.]))

#### Read csv with DataHandler

In [11]:
data_csv = DataHandler.read_dataset(
    path=dataset_path_csv,
    data_type="numpy",
)
data_csv[0][:5], data_csv[1][:5]


(array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2]]),
 array([0., 0., 0., 0., 0.]))

### DataHandler w/ Pandas and parquet format

#### Writes data to temporary (tmp) folder with parquet

In [12]:
dataset_path_parquet = str("./tmp/dataset.parquet")
dataset.to_parquet(dataset_path_parquet)


#### Read parquet with DataHandler

In [13]:
data_parquet = DataHandler.read_dataset(
    path=dataset_path_parquet,
    data_type="numpy",
)
dataset.loc[:, dataset.columns != "target"].to_numpy()[:5], \
dataset["target"].to_numpy()[:5]


(array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2]]),
 array([0., 0., 0., 0., 0.]))

## DataHandler write with Pandas

Since beforehand we already knows what should be read after a successful write, we will now write the same content using DataHandler and then read the data to see if they match .

In [14]:
iris = datasets.load_iris()
dataset = DataFrame(
    data=c_[iris["data"], iris["target"]],
    columns=iris["feature_names"] + ["target"],
)
dataset.head()


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0     0.0  
1     0.0  
2     0.0  
3     0.0  
4     0.0

### DataHandler w/ Pandas and csv format

In [15]:
DataHandler.save_dataset(
    dataset=dataset,
    path=dataset_path_csv,
)

In [16]:
DataHandler.read_dataset(
    path=dataset_path_csv,
    data_type="pandas",
).head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0     0.0  
1     0.0  
2     0.0  
3     0.0  
4     0.0

### DataHandler w/ Pandas and parquet format

In [17]:
DataHandler.save_dataset(
    dataset=dataset,
    path=dataset_path_parquet,
)

In [18]:
DataHandler.read_dataset(
    path=dataset_path_parquet,
    data_type="pandas",
).head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0     0.0  
1     0.0  
2     0.0  
3     0.0  
4     0.0

## DataHandler write with Numpy Array

### Behaviour that we would like to replicate w/ Numpy Arrays
The results should match. When dealing with cloud, we use s3fs to abstract the same pattern (you can check the tests folder for more indepth garantees that DataHandler works similarly with AWS cloud resources, such as buckets).

In [20]:
iris = datasets.load_iris()
dataset = DataFrame(
    data=c_[iris["data"], iris["target"]],
    columns=iris["feature_names"] + ["target"],
)
dataset.head()


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0     0.0  
1     0.0  
2     0.0  
3     0.0  
4     0.0

In [40]:
X, y = dataset.loc[:, dataset.columns != "target"].to_numpy()[:5], \
dataset["target"].to_numpy()[:5]
X, y

(array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2]]),
 array([0., 0., 0., 0., 0.]))

In [46]:
columns=iris["feature_names"] + ["target"]
arr = np.column_stack([X, y])
arr, columns

(array([[5.1, 3.5, 1.4, 0.2, 0. ],
        [4.9, 3. , 1.4, 0.2, 0. ],
        [4.7, 3.2, 1.3, 0.2, 0. ],
        [4.6, 3.1, 1.5, 0.2, 0. ],
        [5. , 3.6, 1.4, 0.2, 0. ]]),
 ['sepal length (cm)',
  'sepal width (cm)',
  'petal length (cm)',
  'petal width (cm)',
  'target'])

### DataHandler w/ Numpy Array and csv format

In [55]:
DataHandler.save_dataset(
    dataset=arr,
    path=dataset_path_csv,
    columns=columns
)

In [56]:
DataHandler.read_dataset(
    path=dataset_path_csv,
    data_type="pandas",
).head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0     0.0  
1     0.0  
2     0.0  
3     0.0  
4     0.0

### DataHandler w/ Numpy Array and parquet format

In [57]:
DataHandler.save_dataset(
    dataset=arr,
    path=dataset_path_csv,
    file_format = "parquet",
    columns=columns
)

In [58]:
DataHandler.read_dataset(
    path=dataset_path_parquet,
    data_type="pandas",
).head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0     0.0  
1     0.0  
2     0.0  
3     0.0  
4     0.0